### ISSUE TITLE
Use httpotion ~> 3.0.0 for elixir 1.3.x

### ISSUE THREAD

**Issue by aisrael** [zabirauf/elixir_wit#2]
`elixir_wit` currently depends on `{:httpotion, "~> 2.2.0"}`. However, under elixir 1.3.x `httpotion` `2.2.x` has a [known issue](https://github.com/myfreeweb/httpotion/issues/87), which was fixed in `httpotion` `~> 3.0.0`

**Comment by zabirauf** [comment]
Updated the elixir_wit package to 0.2.0 with the updated httpotion dependency
