### ISSUE TITLE
function Map.update/3 is undefined or private in Wit.Client.Deserializer

### ISSUE THREAD

**Issue by micahwedemeyer** [zabirauf/elixir_wit#6]
On [line 80](https://github.com/zabirauf/elixir_wit/blob/master/lib/wit_client.ex#L80) there's a call to `Map.update/3`. This gives me the error in the subject line.

Looking in the Elixir docs, there is a `Map.update!/3` and a `Map.update/4`. It seems like this could be a typo, but maybe I'm missing something?

**Comment by micahwedemeyer** [comment]
Hmm, looks like it's a bit bigger than I thought. Perhaps the `message` function is based on an older response to the `/message` Wit call, because I don't see anything in their returned response about `outcomes`. Looking at one of the deprecated calls, I do see `outcomes` in there.

I didn't see anything on the blog about this specifically, but I'm assuming `outcomes` is deprecated. I guess I'll ask in the Facebook group.

**Comment by zabirauf** [comment]
If there is no outcomes in message anymore then we need to change the model as well to remove it in pull request https://github.com/zabirauf/elixir_wit/pull/7

**Comment by micahwedemeyer** [comment]
Fixed in #9
